In [46]:
import gurobipy as gp
import numpy as np
from gurobipy import GRB

https://math.stackexchange.com/questions/1226186/recovering-the-optimal-primal-solution-from-dual-solution?rq=1

In [47]:
A = np.array([
    [3, 1, 2, 4, 1],
    [2, 3, 1, 4, 2]
])
b = np.array([6, 5])
c = np.array([2, 3, 1, 4, 1])

In [59]:
m = gp.Model("mip")
# x = m.addMVar(len(c), vtype=GRB.BINARY, name="x")
x = m.addMVar(len(c), lb=0, name="x")
m.setObjective(c @ x)
m.addConstr(A @ x >= b)
m.write("mip1.lp")

In [60]:
m.optimize()
for v in m.getVars():
    print(v.varName, v.x)

Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 2 rows, 5 columns and 10 nonzeros
Model fingerprint: 0x28cafb34
Coefficient statistics:
  Matrix range     [1e+00, 4e+00]
  Objective range  [1e+00, 4e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [5e+00, 6e+00]
Presolve removed 0 rows and 1 columns
Presolve time: 0.01s
Presolved: 2 rows, 4 columns, 8 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   2.750000e+00   0.000000e+00      0s
       2    3.6666667e+00   0.000000e+00   0.000000e+00      0s

Solved in 2 iterations and 0.01 seconds (0.00 work units)
Optimal objective  3.666666667e+00
x[0] 0.0
x[1] 0.0
x[2] 2.3333333333333335
x[3] 0.0
x[4] 1.3333333333333333


In [51]:
np.array([1,2,3]) @ np.array([2,3,4])

20

In [57]:
md = gp.Model("dual")
y = md.addMVar(len(b), lb=0, name="y")
md.setObjective(b @ y, GRB.MAXIMIZE)
md.addConstr(A.T @ y <= c)
md.write("dual.lp")

In [58]:
md.optimize()
for v in md.getVars():
    print(v.varName, v.x)

Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 5 rows, 2 columns and 10 nonzeros
Model fingerprint: 0x9659a8f0
Coefficient statistics:
  Matrix range     [1e+00, 4e+00]
  Objective range  [5e+00, 6e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 4e+00]
Presolve removed 1 rows and 0 columns
Presolve time: 0.00s
Presolved: 4 rows, 2 columns, 8 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    5.0000000e+00   1.997000e+00   0.000000e+00      0s
       3    3.6666667e+00   0.000000e+00   0.000000e+00      0s

Solved in 3 iterations and 0.01 seconds (0.00 work units)
Optimal objective  3.666666667e+00
y[0] 0.3333333333333333
y[1] 0.33333333333333337


In [61]:
md.getVars()

[<gurobi.Var y[0] (value 0.3333333333333333)>,
 <gurobi.Var y[1] (value 0.33333333333333337)>]

In [64]:
A.T.dot([v.x for v in md.getVars()]) - c

array([-0.33333333, -1.66666667,  0.        , -1.33333333,  0.        ])

In [73]:
a = np.array(A.T.dot([v.x for v in md.getVars()]) - c).T
b = np.array([0, 0, 0, 0, 0])

In [74]:
a

array([-0.33333333, -1.66666667,  0.        , -1.33333333,  0.        ])

In [78]:
np.linalg.lstsq([a], [0], rcond=None)

(array([0., 0., 0., 0., 0.]), array([], dtype=float64), 1, array([2.1602469]))

In [80]:
b = np.array([6, 5])

In [81]:
A, b

(array([[3, 1, 2, 4, 1],
        [2, 3, 1, 4, 2]]),
 array([6, 5]))

In [82]:
np.linalg.solve([[2, 1], [1, 2]], b)

array([2.33333333, 1.33333333])