In [1]:
import numpy as np

In [10]:
A = np.array([
    [1, 2, 4],
    [3, 1, 4],
    [2, 2, 2]
])
b = np.array([2, 5, 1])

In [11]:
R = list(range(A.shape[0]))
R

[0, 1, 2]

# Primal 1 (Chvatal basically)

In [5]:
M = [sum(A[i]) / b_i for i, b_i in enumerate(b)]
M
# if some row is less than one, problem is infeasible

[3.5, 1.6, 6.0]

In [8]:
i = np.argmax(M)
i

2

In [13]:
j = np.argmax(A[i])
j

0

In [14]:
b = b - A[:,j]
b

array([ 1,  2, -1])

In [18]:
A = np.delete(A, j, axis=-1)
A

array([[2, 4],
       [1, 4],
       [2, 2]])

In [19]:
M = [sum(A[i]) / b_i for i, b_i in enumerate(b)]
M

[6.0, 2.5, -4.0]

In [21]:
i = np.argmax(M)
j = np.argmax(A[i])
i, j

(0, 1)

In [13]:
def chvatal(A, b):
    cover = []
    A0 = A
    b0 = b
    while (np.any(b > 0)):
        M = [sum(A[i]) / b_i for i, b_i in enumerate(b)]
        i = np.argmax(M)
        j = np.argmax(A[i])
        cover.append(j)
        b = b - A[:,j]
        A[:,j] -= A[:,j]
    assert 
    return cover, len(cover)

In [24]:
A = np.array([
    [1, 2, 4, 3, 2, 1],
    [3, 1, 4, 1, 1, 2],
    [2, 2, 2, 1, 4, 6],
    [1, 2, 3, 4, 3, 1]
])
b = np.array([6, 7, 5, 6])

In [25]:
cov = np.array([5, 3, 2])

In [26]:
x = np.zeros((A.shape[-1],))
x

array([0., 0., 0., 0., 0., 0.])

In [27]:
x[cov] = 1
x

array([0., 0., 1., 1., 0., 1.])

In [28]:
A @ x

array([8., 7., 9., 8.])

In [29]:
np.all(A @ x >= b)

True

In [15]:
cover, cost = chvatal(A, b)
cover, cost

([5, 3, 2], 3)

# Primal 2 (Dobson)

In [36]:
A = np.array([
    [1, 2, 7, 3, 2, 1],
    [3, 1, 4, 1, 1, 2],
    [2, 2, 2, 1, 4, 6],
    [1, 2, 3, 4, 3, 1]
])
b = np.array([6, 7, 5, 6])

In [43]:
def primal_heur2(A, b):
    cover = []
    while (np.any(b > 0)):
        A = np.minimum(A.T, b).T
        k = np.argmin(1 / np.sum(A, axis=0))
        cover.append(k)
        b = b - A[:,k]
        A = np.delete(A, k, axis=-1)
    return cover, len(cover)

In [44]:
primal_heur2(A, b)

([2, 3, 0], 3)

# Primal 3 (Hall, Hochbaum)

In [58]:
def primal_heur3(A, b):
    cover = []
    while (np.any(b > 0)):
        rsum = np.sum(A, axis=-1)
        space = rsum - b
        
        f = [sum([(b[i] * A[i][j]) / (space[i]) for i in np.where(b > 0)[0]]) 
             for j in range(A.shape[-1])]

        k = np.argmax(f)
        cover.append(k)
        b = b - A[:,k]
        A = np.delete(A, k, axis=-1)
    return cover, len(cover)

In [59]:
A = np.array([
    [1, 2, 7, 3, 2, 1],
    [3, 1, 4, 1, 1, 2],
    [2, 2, 2, 1, 4, 6],
    [1, 2, 3, 4, 3, 1]
])
b = np.array([6, 7, 5, 6])

In [60]:
primal_heur3(A, b)

([2, 4, 2], 3)